name: PR
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
env:
  RELEASE: release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Build pistache circa 2017
        run: |
          mkdir pistache/build
          pushd pistache/build
          cmake ..
          make -j4 && sudo make install
          popd
          
      - name: Debug build of all snakes
        run: |
          mkdir build
          mkdir build-opt
          mkdir run_basic
          mkdir run_boost
          make -j4       
